spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/footballmanager
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/database/project-changelogs.xml
    url: jdbc:postgresql://db:5432/footballmanager
    user: postgres
    password: postgres