server:
  port: 8080
spring:
  profiles:
    active: docker
  application:
    name: "footballManager"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true