server:
  port: 8080
spring:
    application:
      name: "footballManager"
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/footballmanager
      username: postgres
      password: postgres
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
    flyway:
      baseline-on-migrate: true
      default-schema: public