networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres:17-alpine
    container_name: footballmanager_db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: footballmanager
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    container_name: footballmanager_app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:
